### ISSUE TITLE
Do you know what's going on?Because it has not been used before TypeScript?

### ISSUE THREAD

**Issue by zhangenming** [ryanatkn/react-mobx-typescript-experiments#2]
> react-mobx-typescript-experiments@0.1.8 start /Users/kaixunkejigcs/Desktop/mobx
> webpack-dev-server --progress --colors --inline

 70% 1/1 build modulesevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-mobx-typescript-experiments@0.1.8 start: `webpack-dev-server --progress --colors --inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-mobx-typescript-experiments@0.1.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kaixunkejigcs/.npm/_logs/2018-01-15T03_16_52_481Z-debug.log

**Comment by ryanatkn** [comment]
It looks like something else is already using port 8080, the default port for webpack dev server. This could be another app you're running. The easiest thing you could try is `npm start -- --port 8081` (or some other port).

Unrelated to the problem you mentioned above, the build was also failing because it was loading a tslint config for a newer version of tslint - it compiles for me now, but with warnings that you can safely ignore. Make sure you pull the new version before trying.

**Comment by zhangenming** [comment]
thanks, you are right
can close
