### ISSUE TITLE
demo SFC

### ISSUE THREAD

**Issue by yzorg** [ryanatkn/react-mobx-typescript-experiments#3]
The (MobX docs)[https://mobx.js.org/refguide/observer-component.html#stateless-function-components] show how to use SFC (pure functional) using JSX but not in TSX.  I'm having a hard time finding the typescript syntax for SFCs with MobX observer().

There seem to be a few of your examples that could have been written as SFCs but weren't.  Was that intentional?  If so, why did you avoid them?

**Comment by yzorg** [comment]
This medium article (from a guy I'd listen to, Cory House), suggests teams should not use SFCs to reduce git churn and make the codebase more consist.  Did you avoid SFC for the same reasons?
https://medium.freecodecamp.org/7-reasons-to-outlaw-reacts-functional-components-ff5b5ae09b7c

**Comment by ryanatkn** [comment]
edit: some of this is outdated with React 16.6 - if you read it, be sure to also see my reply below

Thanks for the question - it was helpful for me to think through this, and I like the article you linked. That includes all but one of the reasons I tend to not use SFCs, though I wouldn't recommend my opinion or style to anyone else. Like the article says, they add friction for no performance benefit - in fact, quite the opposite, they can come with significant performance losses depending on your use case. I found [his earlier article](https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc) arguing the opposite to be unconvincing, despite the fact that SFCs are a recommended best practice. There's something to be said for using the simple option when you have the simple case, but there's something else that bugs me about SFCs. I'm hung up on performance.

A major reason I prefer classes that the article didn't mention, perhaps _the main_ reason, is that they're a performance win in many or most cases, in terms of runtime CPU cycles and garbage (but not memory, which is a tradeoff I'll almost always make in web apps). Disclaimer: I know some prominent people in the React community have specifically argued that what I'm about to say is an unimportant premature optimization. SFCs force you to create new callback functions, when passing function props to child components, every time they render if you want to bind any data to the function, like props or other data with a closure or `.bind`. With classes, you can use arrow instance methods to create those functions once when the component is created, instead of every re-render.

Is this a huge cost? Have I profiled? It depends, and no I haven't profiled. SFCs prevent `shouldComponentUpdate` optimizations like what `React.PureComponent`  offers whenever they pass an inlined or freshly bound function (see [fbjs/lib/shallowEqual](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js), which is used by both `PureComponent` and `recompose#pure`, which will interpret inlined functions and new closures as props changing, forcing the entire subtree to render and reconcile), and though you could write a custom version that ignores functions, that could cause subtle bugs due to closures. Missing this optimization can have a major impact depending on the app, and in some of my apps would mean the difference between rendering and reconciling a few DOM elements versus hundreds. I want to note that our personal context is important when discussing these things - I often write apps that render a lot of elements where lots of isolated little changes occur, so re-rendering the entire page is not the common case and can be quite expensive.

 And beyond `shouldComponentUpdate`, creating new functions on every render unavoidably costs more CPU time. I feel that this waste is worth avoiding because it's trivial to do so in most cases, and keeps my render methods cleaner to boot, free of inline anonymous functions. I cut my teeth as a programmer by making video games, and perhaps that has forever polluted my mind with a premature performance obsession, but the phrase "death by a thousand cuts" comes to mind, so no amount of profiling is likely to pierce my thick head on this issue. Part of it is philosophical - I see it as being respectful of my users - why be wasteful for such a small and dubious developer convenience? Again, I don't expect others to think this way - it's just ingrained in how I approach software, and it's a very tough perspective to maintain as a web developer, where our technologies often seem so wasteful, and there are always tradeoffs of developer convenience to be made, so I'm not above being wasteful in any case. In other words, there's probably plenty of hypocritical irony to be found in the above justifications. :)

Also a quick note - if you're wrapping your SFC with certain recompose functions like `pure` or MobX's `observer`, they're being wrapped with classes under the hood anyway. That makes SFCs a lot less lightweight than they appear.

I migrated [the AppHeader component over to an SFC](https://github.com/ryanatkn/react-mobx-typescript-experiments/blob/gh-pages/src/components/AppHeader/index.tsx). I had to update to the latest MobX version to get the types to work correctly (the previously installed version 2.x was always inferring `any` for props even when specified), but this looks good to me - the only type annotation is `: Props`, and the prop interface could be inlined to be more compact.

**Comment by yzorg** [comment]
> ... if you're wrapping your SFC with certain recompose functions like pure or MobX's observer, they're being wrapped with classes under the hood anyway.

That's the main reason for me.  I'm not a "career" React guy, at this point if I'm using React with a state container it's going to be MobX, and `@observer` wraps the SFC in a class anyway.

(Yes, repeating, but I think it's info that needs to be in your feed and my feed.)

**Comment by ryanatkn** [comment]
Some of the information above is now outdated, and I've shifted my perspective somewhat since writing it. React 16.6 added the `memo` helper, giving SFCs (now called "function components") an equivalent to `shouldComponentUpdate` without adding the bulk of a class wrapper. [Here's the code](https://github.com/facebook/react/blob/master/packages/react/src/memo.js) for how it works. React 16.7 will introduce [hooks](https://reactjs.org/docs/hooks-intro.html), which will probably make me switch from classes to function components altogether.

A takeaway lesson for me is that following official best practices can have benefits in the future, even if they're not optimal today. Existing code that uses function components may be able to take advantage of the new performance improvements without any changes if the underlying library switches over. It looks like [Mobx will use hooks soon](https://twitter.com/mweststrate/status/1055532227939966976), for example. The React team has also said that Mobx does not fit their design philosophy for the future of React (but Immer and immutable data do), so we may see more situations in the future where libraries like Redux have new benefits over Mobx.

Many of the UIs I create have hundreds of DOM elements with small rapid changes, sometimes every frame, so I tend to optimize for that use case. (think dashboards and game UIs) I've run into many situations where re-rendering the entire UI takes more than 16ms until I use `shouldComponentUpdate`, and Mobx makes efficient granular re-rendering effortless. One major tradeoff of optimizing for redraws is that the initial render of a full page will be slower, especially compared to a UI composed entirely of function components. This tradeoff works for many of my use cases, but I'd guess that the vast majority of developers want the opposite tradeoff, to optimize for the initial render, and aren't as sensitive to redraws that may take more than a frame.

The optimizing I'm doing today is necessary for a smooth UX, but I may rethink my approach entirely once React's concurrent rendering arrives (previously "async" rendering). [Here's an example](https://twitter.com/jlongster/status/1054554506736910336) of how impactful it can be. Concurrent rendering prevents those >16ms updates from causing dropped frames and jank. In that world, it's possible that using only function components, hooks, and careful use of `memo` is best for my use case. And in the future, things like wasm, parallelism, and optimizers (like [prepack](https://github.com/facebook/prepack) and [Babel plugins](https://github.com/motiz88/babel-plugin-transform-hoist-nested-functions)) may solidify that advantage. There's a balance each of us needs to find between our user's experience, our own development experience, the suggested best practices of our frameworks, and all of these factors both today and in some unknown future. I've decided to give more weight to the recommendations of framework authors.
